title: Sovereign Cloud Stack
tagline: Sovereign Cloud Stack (SCS) is federated cloud technology built entirely with Open Source Software â€” putting users and providers in control.
description: Sovereign Cloud Stack (SCS) is a network of existing and future providers of standardized sovereign cloud and container infrastructure to join forces in defining, implementing and operating a fully open, federated, compatible platform. By joining forces, the platform can support a healthy ecosystem for service and application developers and strengthen the digitalization efforts in Europe without creating large risks to lose control over the technology and the data.

permalink: pretty

languages: ["en", "de"]
exclude_from_localizations: ["assets"]

sass:
  sass_dir: /assets/css/_sass
  style: compressed

include:
  - _pages

exclude:
  - .sass-cache

twitter:
  username: scs_osballiance
  card: summary

social:
  name: Sovereign Cloud Stack
  links:
    - https://twitter.com/scs_osballiance
    - https://www.linkedin.com/showcase/sovereigncloudstack
    - https://github.com/SovereignCloudStack

plugins:
  - jekyll-multiple-languages-plugin
  #- jekyll-redirect-from   # redirect from /Jobs/ to /jobs/ leads to a redirection loop on Windows platforms due to case-insensitive filesystem
  - jekyll-seo-tag
  - jekyll-last-modified-at
